<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>SampleStore.Data.EF.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleStore.Common\SampleStore.Common.csproj" />
    <ProjectReference Include="..\SampleStore.Data.Entities\SampleStore.Data.Entities.csproj" />
    <ProjectReference Include="..\SampleStore.Data\SampleStore.Data.csproj" />
  </ItemGroup>

</Project>
