<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleStore.Common\SampleStore.Common.csproj" />
    <ProjectReference Include="..\SampleStore.Data.Entities\SampleStore.Data.Entities.csproj" />
    <ProjectReference Include="..\SampleStore.Data\SampleStore.Data.csproj" />
  </ItemGroup>

</Project>
