<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleStore.Mapping\SampleStore.Mapping.csproj" />
    <ProjectReference Include="..\SampleStore.UI\SampleStore.UI.csproj" />
  </ItemGroup>

</Project>
