<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>SampleStore.Identity.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleStore.Common\SampleStore.Common.csproj" />
    <ProjectReference Include="..\SampleStore.Data.Entities\SampleStore.Data.Entities.csproj" />
    <ProjectReference Include="..\SampleStore.Data.Extensions\SampleStore.Data.Extensions.csproj" />
    <ProjectReference Include="..\SampleStore.Data\SampleStore.Data.csproj" />
  </ItemGroup>

</Project>
